main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Portfolio
    pageRef: /portfolio
    weight: 20
  - name: About Me
    pageRef: /aboutme
    weight: 30
  - name: Contact
    pageRef: /contact
    weight: 40
#- name: Films
#  pageRef: /films
#  weight: 3\
