main:
  - name: Home
    url: /#intro
    weight: 10
    params:
      id: "top"
      class: "icon solid fa-home"
  - name: Portfolio
    url: /#portfolio
    weight: 20
    params:
      id: "portfolio"
      class: "icon solid fa-th"
  - name: About Me
    url: /#about
    weight: 30
    params:
      id: "about"
      class: "icon solid fa-user"
  - name: Contact
    url: /#contact
    weight: 40
    params:
      id: "contact"
      class: "icon solid fa-envelope"
#- name: Films
#  pageRef: /films
#  weight: 3\
