


# -----------------------------------------------

# how the content will get rendered 

# Hero section --- will be in configure from config.toml

# Portfolio section --- will get rendered form "content/poyect.md"

# Aobut me section --- will be in configure from config.toml

# Contac me Section --- will be in configure from config.toml

# -----------------------------------------------

