# add future configurations in these file

#configuration for changing title
<title>Prologue by HTML5 UP</title>


#configuration for changing  footer title
<ul class="copyright">
    <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
</ul>

